### PR TITLE
Update python bindings

### PR DESCRIPTION
**Pull request by prithvirajkadiyala**

### CODE REVIEW

**Comment by prithvirajkadiyala** [comment]
While trying to merge the code into the existing code. I am getting the following errors.

Seems like there is an issue with importing opencv2

```
/home/pi/test/libwallaby-master/src/camera.cpp: In member function ‘bool Camera::Device::open(int, Resolution, Model)’:
/home/pi/test/libwallaby-master/src/camera.cpp:331:17: error: expected type-specifier
     m_cap = new cv::VideoCapture_K(0);
                 ^
/home/pi/test/libwallaby-master/src/camera.cpp:342:18: error: expected primary-expression before ‘.’ token
     m_cap->set(cv.CAP_PROP_BUFFERSIZE,10) ;
                  ^
/home/pi/test/libwallaby-master/src/camera.cpp:345:18: error: expected primary-expression before ‘.’ token
     m_cap->set(cv.CAP_PROP_BUFFERSIZE, 4);  // minimize processing

```

**Comment by prithvirajkadiyala** [comment]
@EugeneDMyers Can you check if your controller has opencv installed and what version of it?

Because I don't see opencv installed on my controller. If you have opencv or alternative installed, Can you point me to what version and where did you get that from?

**Comment by EugeneDMyers** [comment]
I’m in the process of getting my wombat up to date so I can address the video resolution question.

However, I’m starting with the SD from last July, so I image what I should wind up with would be the same as yours.

I can check my wallaby to see which version that it is (that version should have came with the original wallaby), except that the libwallaby should not link unless you have opencv installed.

Can’t check on it until I get home tonight, however.

What issues are you having?

     gene

**Comment by prithvirajkadiyala** [comment]
I have put the error messages in the above comment. Seems like it has importing issues for the opencv library. 

The current and latest version 25.7 is available on Dropbox at the following link

> https://www.dropbox.com/s/rdrph4owl4t7xjw/Wombat-v25.7.img?dl=0

I am trying to build the libwallaby branch named "Update-python-bindings"  

> https://github.com/kipr/libwallaby/tree/update-python-bindings

**Comment by EugeneDMyers** [comment]
I’ll apply that image tonight and look into it. (it might take two nights as copying images only raw media seems to be a glacial process)

I did notice merge issues for the master, which told me that there seems some header file problem.

I did take a module from opencv v4 and modified it to work with with the wallaby (it’s opencv version was V2), so its probably something that it was depending on in the wallaby that is not on the wombat, which I provided in some form.

    gene

**Comment by EugeneDMyers** [comment]
> While trying to merge the code into the existing code. I am getting the following errors.
> 
> Seems like there is an issue with importing opencv2
> 
> ```
> /home/pi/test/libwallaby-master/src/camera.cpp: In member function ‘bool Camera::Device::open(int, Resolution, Model)’:
> /home/pi/test/libwallaby-master/src/camera.cpp:331:17: error: expected type-specifier
>      m_cap = new cv::VideoCapture_K(0);
>                  ^
> /home/pi/test/libwallaby-master/src/camera.cpp:342:18: error: expected primary-expression before ‘.’ token
>      m_cap->set(cv.CAP_PROP_BUFFERSIZE,10) ;
>                   ^
> /home/pi/test/libwallaby-master/src/camera.cpp:345:18: error: expected primary-expression before ‘.’ token
>      m_cap->set(cv.CAP_PROP_BUFFERSIZE, 4);  // minimize processing
> ```

These look like you have attempted to merge into master and some chunks did not get fully merged. 

cv:: VideoCapture_K() is an override class that should have been merged into the beginning of (lines ~35-80) and the line numbers of the error messages indicate that it did not get merged.  Go to branch CameraFix and you should be able to see what is generally missing.  The other errors are of the same issue.

**Comment by prithvirajkadiyala** [comment]
Another pull request for the same has been issued and been looked into.
Look into #104 for further details with merging

**Pull request closed without merging**
