### PR TITLE
load and play songs on the create

### PR DESCRIPTION
**Pull request by chrehall68**
Done:
- [x] update the source code: create.hpp, create_c.h, create.cpp, create_c.cpp
- [x] test build - successful build
- [x] test deploy - successful deployment 
- [x] try out on roomba - tested out all new functions (get_create_song_playing, get_create_song_number, create_play_song, and create_load_song)

Ready for deployment!

### CODE REVIEW

**Comment by chrehall68** [comment]
successful build screenshot (the code built successfully, so I opened up documentation):
image

**Comment by chrehall68** [comment]
successfully deployed to a wombat (emphasis on how the web address is 192.168.125.1:8888/...)
image
And when you try to run it (without being connected to a create), you get the neat error message
image
All that's left to do now is test on a real create.

**Comment by chrehall68** [comment]
Tested out on create. It works!!! 😄

**Comment by Zacharyprime** [comment]
Tested and works!
Great work!

**Pull request merged**
